In [66]:
import numpy as np
import pandas as pd
import scipy.io as sp
from matplotlib import pyplot as plt
#import seaborn as sns
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve


In [67]:
dataSet = sp.loadmat('breastw.mat') #On charge le dataset
print(type(dataSet))


<class 'dict'>


In [68]:
X = dataSet['X'] #On extrait la donnée du champ 'X' du dictionnaire
print('dimension de X', X.shape )
Y = dataSet['y'] #On extrait les données liées à la clé 'target'
print(np.shape(Y))
print(Y)

dimension de X (683, 9)
(683, 1)
[[0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [

In [69]:
print('dimention de y', Y.shape)


dimention de y (683, 1)


In [70]:

def perceptron_sgd(X, Y):
    w = np.zeros(len(X[0])) # initialisation du poids avec un vecteur de 0
    eta = 1 #on set le learning rate à 1
    epochs = 30 #set du nombre d'epoch

    for t in range(epochs):
        for i, x in enumerate(X):
            if (np.dot(X[i], w)*Y[i]) <= 0:
                w = w + eta*X[i]*Y[i]

    return w


w = perceptron_sgd(X,Y)
print(w)
print('dimention de w', w.shape)

[ 8. 10. 10.  8.  7. 10.  9.  7.  1.]
dimention de w (9,)


In [71]:
#label = np.zeros(Y.shape)
t = np.zeros((len(X),1))
#print(t)
for i, x in enumerate(X): #pour toutes les lignes de X
    #t = X[i]   
    t[i]= w[0]*X[i,0]+w[1]*X[i,1]+w[2]*X[i,2]+w[3]*X[i,3]+w[4]*X[i,4]+w[5]*X[i,5]+w[6]*X[i,6]+w[7]*X[i,7]+w[8]*X[i,8]

print(t)

[[127.]
 [351.]
 [121.]
 [354.]
 [135.]
 [608.]
 [185.]
 [113.]
 [ 89.]
 [120.]
 [ 88.]
 [ 94.]
 [233.]
 [115.]
 [487.]
 [298.]
 [110.]
 [119.]
 [441.]
 [135.]
 [398.]
 [450.]
 [102.]
 [ 95.]
 [276.]
 [105.]
 [118.]
 [ 94.]
 [ 97.]
 [ 95.]
 [103.]
 [444.]
 [111.]
 [112.]
 [ 94.]
 [532.]
 [174.]
 [394.]
 [331.]
 [300.]
 [507.]
 [313.]
 [521.]
 [ 87.]
 [407.]
 [ 86.]
 [135.]
 [415.]
 [284.]
 [242.]
 [365.]
 [445.]
 [435.]
 [372.]
 [444.]
 [254.]
 [293.]
 [275.]
 [318.]
 [ 96.]
 [479.]
 [272.]
 [ 86.]
 [256.]
 [119.]
 [374.]
 [459.]
 [102.]
 [138.]
 [451.]
 [186.]
 [477.]
 [293.]
 [131.]
 [116.]
 [146.]
 [131.]
 [101.]
 [152.]
 [118.]
 [137.]
 [157.]
 [494.]
 [434.]
 [326.]
 [440.]
 [119.]
 [109.]
 [ 95.]
 [101.]
 [119.]
 [ 86.]
 [103.]
 [ 95.]
 [ 93.]
 [127.]
 [459.]
 [511.]
 [387.]
 [236.]
 [129.]
 [265.]
 [576.]
 [257.]
 [502.]
 [479.]
 [100.]
 [403.]
 [166.]
 [348.]
 [421.]
 [534.]
 [161.]
 [117.]
 [208.]
 [446.]
 [111.]
 [131.]
 [113.]
 [139.]
 [535.]
 [351.]
 [472.]
 [ 86.]
 [423.]
