In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.model_selection import StratifiedKFold
import scipy.io as sp
from sklearn.ensemble import IsolationForest, BaggingClassifier

dataSet = sp.loadmat('breastw.mat')
X = dataSet['X']
y = dataSet['y']
#print(y)

In [2]:
model = IsolationForest(contamination=0.01)
model.fit(X)
outliers = model.predict(X) == -1 
outliers
model.predict(X)

#plt.scatter(X[:,0], X[:, 1], c=model.predict(X))

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1

In [3]:
liste = [19, 1, 23, 18, 46, -1]
# affichage de la liste
print("liste originale : " + str(liste))
model1 = [0 if elem == 1 else elem for elem in model]
print("nouvelle liste : " + str(model1))
model2 = [1 if elem == -1 else elem for elem in model]
print("nouvelle liste : " + str(model2))

liste originale : [19, 1, 23, 18, 46, -1]
nouvelle liste : [ExtraTreeRegressor(max_depth=8, max_features=1, random_state=282393003), ExtraTreeRegressor(max_depth=8, max_features=1, random_state=967514132), ExtraTreeRegressor(max_depth=8, max_features=1, random_state=636055435), ExtraTreeRegressor(max_depth=8, max_features=1, random_state=1994474412), ExtraTreeRegressor(max_depth=8, max_features=1, random_state=878981588), ExtraTreeRegressor(max_depth=8, max_features=1, random_state=1545758580), ExtraTreeRegressor(max_depth=8, max_features=1, random_state=1883307518), ExtraTreeRegressor(max_depth=8, max_features=1, random_state=838960777), ExtraTreeRegressor(max_depth=8, max_features=1, random_state=1788071259), ExtraTreeRegressor(max_depth=8, max_features=1, random_state=99690411), ExtraTreeRegressor(max_depth=8, max_features=1, random_state=955970959), ExtraTreeRegressor(max_depth=8, max_features=1, random_state=170096006), ExtraTreeRegressor(max_depth=8, max_features=1, random_state=

In [9]:
from sklearn.metrics import classification_report, precision_score, confusion_matrix, roc_curve, precision_recall_curve
from sklearn import metrics
from sklearn.metrics import roc_curve, auc

skf = StratifiedKFold(n_splits=2)
skf.get_n_splits(X, y) #get and split return n split

for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index,:], X[test_index,:]
    y_train, y_test = y[train_index], y[test_index]
    model = IsolationForest(contamination=0.15, n_estimators=10)
    model.fit(X_train)
    #print(model.predict(X_test))
    #model1 = [0 if elem == 1 else elem for elem in model.predict(X_test)]
    #print("nouvelle liste : " + str(model1))
    #model2 = [1 if elem == -1 else elem for elem in model1]
    #print("nouvelle liste : " + str(model2))
    y_pred=model.predict(X_test)
    y_pred[y_pred>0]=0
    y_pred[y_pred<0]=1
    y_pred1=model.fit_predict(X_test)
    y_pred1[y_pred1>0]=0
    y_pred1[y_pred1<0]=1
    #y_pred =  model2
    #plt.figure(figsize=(10,7))
    #plt.subplot(121)
    #plt.title("Prédiction avec KMeans")
    #plt.scatter(X[:,0],X[: , 1], c=y_pred)
    #plt.scatter(model.cluster_centers_[:,0],model.cluster_centers_[:,1], c='r')
    #plt.subplot(122)
    #plt.title("Répartition initiale")
    #plt.scatter(X[:,0], X[:,1], c=y)
    #model.inertia_ 
    #if precision_score(y_test,y_pred)< 0.15:
    #y_pred = np.array([0 if label == 1 else 1 for label in y_pred])
    #print (y_pred)
    #print (y_test)
    
    print(classification_report(y_test,y_pred))
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test,y_pred1))
    print(confusion_matrix(y_test, y_pred1))
    
    
    #isolation_fpr, isolation_tpr, threshold = roc_curve(y_test, y_pred)
    #auc_isolation = auc(isolation_fpr, isolation_tpr)
    #plt.figure(figsize=(5, 5), dpi=100)
    #plt.plot(isolation_fpr, isolation_tpr, marker='.', label='Isolation (auc = %0.3f)' % auc_isolation)
    #plt.xlabel('False Positive Rate -->')
    """plt.ylabel('True Positive Rate -->')
    plt.legend()
    plt.show()
       """
        

              precision    recall  f1-score   support

           0       0.80      0.98      0.88       222
           1       0.94      0.53      0.68       120

    accuracy                           0.82       342
   macro avg       0.87      0.76      0.78       342
weighted avg       0.85      0.82      0.81       342

[[218   4]
 [ 56  64]]
              precision    recall  f1-score   support

           0       0.75      0.98      0.85       222
           1       0.92      0.40      0.56       120

    accuracy                           0.78       342
   macro avg       0.84      0.69      0.70       342
weighted avg       0.81      0.78      0.75       342

[[218   4]
 [ 72  48]]
              precision    recall  f1-score   support

           0       0.84      0.99      0.91       222
           1       0.97      0.66      0.78       119

    accuracy                           0.87       341
   macro avg       0.91      0.82      0.85       341
weighted avg       0.89     