In [10]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 

print ('First array:') 
print (a )
print ('\n' ) 

 
#print (np.append(a, [7,8,9]) )
 


print (np.append(a, [[7,8,9]],axis = 0) )
#print (np.append(a, [[5,5,5],[7,8,9]],axis = 1))


First array:
[[1 2 3]
 [4 5 6]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:

data = np.arange(1,13)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])