In [81]:
import numpy as np
import scipy.io as sp
from sklearn.model_selection import train_test_split 
from numpy import concatenate
from sklearn.semi_supervised import LabelPropagation
from sklearn.linear_model import LogisticRegression
from sklearn.mixture import GaussianMixture
from sklearn.metrics import classification_report, roc_auc_score,precision_score
from sklearn.model_selection import StratifiedKFold 
# evaluate label propagation on the semi-supervised learning dataset



dataSet = sp.loadmat('breastw.mat')
X = dataSet['X']
y = dataSet['y']
skf = StratifiedKFold(n_splits=10,shuffle=False)

#for train_index, test_index in skf.split(X,y):
    #i=0
    #X_train, X_test = X[train_index,:], X[test_index,:]
    #y_train, y_test = y[train_index], y[test_index]

    
print(np.shape(X))
y = np.array([-1 if label == 1 else 1 for label in y])
count = (y == -1).sum()
print(count)
x=0
for j in y :
    if i==len(y):
        break
    elif y[i]== -1 :
        X= np.delete(X,obj=i-x,axis=0)
        x=x+1
    i = i+1    
print(np.shape(X))
print(X)
print(x)

(683, 9)
239
(683, 9)
[[ 5  1  1 ...  3  1  1]
 [ 5  4  4 ...  3  2  1]
 [ 3  1  1 ...  3  1  1]
 ...
 [ 5 10 10 ...  8 10  2]
 [ 4  8  6 ... 10  6  1]
 [ 4  8  8 ... 10  4  1]]
0
